### ISSUE TITLE
Add flow control statements?

### ISSUE THREAD

**Issue by drf5n** [gto76/python-cheatsheet#134]
The basic flow control syntax for `if`, `else`, `elif`, `for`, and `while` do not seem to be included.

**Comment by harkabeeparolus** [comment]
According to [The FAQ](https://github.com/gto76/python-cheatsheet/wiki/Frequently-Asked-Questions):
> Q: Why are some basics like '<list> = [<el_1>, <el_2>, ...]' and '<el> = <list>[<int>]' missing?
> 
> A: This cheatsheet is not intended for complete beginners. This way it can save some valuable space. Nonetheless, it tries to be simple enough to be useful for somebody who completed the introductory course. [...]
