### ISSUE TITLE
add persian language to this project

### ISSUE THREAD

**Issue by alirezafazeli8** [gto76/python-cheatsheet#161]
Hi 
How are you?
I want to add the Persian language to this repository, the Persian language has millions of followers in the world, and it's my native language. I can add the Persian language for the Python cheatsheet and Persian people can use this.
What's your comment?

**Comment by gto76** [comment]
Hi.
I'm fine, thank you!

Sounds cool.
I don't intend to merge your changes, so just fork the repository and translate it and I will add a link at the top that will lead to list of available translations (if you finish it).

Also leave a link to this [repository](https://github.com/gto76/python-cheatsheet) and/or [webpage](https://gto76.github.io/python-cheatsheet/) and/or [my homepage](https://gto76.github.io/) somewhere visible.

**Comment by alirezafazeli8** [comment]
thanks 
As soon as I start translating to Persian I tell you.
can you send your email?

**Comment by gto76** [comment]
Ok.
My mail is:
```bash
echo 736f726e6a75726540686f746d61696c2e636f6d0a | xxd -r -p
```

**Comment by alirezafazeli8** [comment]
Thanks 😂😂
