### ISSUE TITLE
List comprehension - order of loop variables

### ISSUE THREAD

**Issue by Lyoug** [gto76/python-cheatsheet#2]
In this section:

-----
```python
out = [i+j for i in range(10) for j in range(10)]
```
#### Is the same as:
```python
out = []
for i in range(10):
    for j in range(10):
        out.append(i+j)
```
-----

The loop variables i and j should be swapped in either the first or the second part. Maybe one of the 10s could even be changed into another value to make it clearer? For instance:
```python
out = [i+j for j in range(5) for i in range(10)]
```
#### Is the same as:
```python
out = []
for i in range(10):
    for j in range(5):
        out.append(i+j)
```

**Comment by gto76** [comment]
Your example does not output same results:

```python
>>> out_a = [i+j for j in range(5) for i in range(10)]
>>> out_b = []
>>> for i in range(10):
...     for j in range(5):
...         out_b.append(i+j)
... 
>>> out_a == out_b
False
>>> out_a
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
>>> out_b
[0, 1, 2, 3, 4, 1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 5, 6, 7, 8, 9, 6, 7, 8, 9, 10, 7, 8, 9, 10, 11, 8, 9, 10, 11, 12, 9, 10, 11, 12, 13]
```

**Comment by Lyoug** [comment]
Yes, my bad, I should have tested this more thoroughly – I assumed I had the correct intuition about this, but it turns out your initial order is the correct one. I’d still suggest changing one of the 10s to something else:
> ```python
> out = [i+j for i in range(10) for j in range(5)]
> ```
> 
> #### Is the same as:
> 
> ```python
> out = []
> for i in range(10):
>     for j in range(5):
>         out.append(i+j)
> ```
Anyway, thank you for this great cheatsheet.

**Comment by gto76** [comment]
Thanks!
