### ISSUE TITLE
Datetime

### ISSUE THREAD

**Issue by farisachugthai** [gto76/python-cheatsheet#24]
```python
from datetime import datetime, strptime
now = datetime.now()
now.month                     # 3
now.strftime('%Y%m%d')        # '20180315'
now.strftime('%Y%m%d%H%M%S')  # '20180315002834'
<datetime> = strptime('2015-05-12 00:39', '%Y-%m-%d %H:%M')
```

The first line has a typo and should be `from datetime import datetime, strftime`.
But you can't import strftime from the root module.

datetime.datetime.now() returns a datetime object, and those can be called with strftime I.E.
```python
from datetime import datetime
datetime.now().strftime('%b')
# --> Feb
```

Simply the first line just needs the last word deleted off. Don't forget the typo in the last line either ;)

I'd take this opportunity to mention a few cool tricks about `from datetime import date` but I'm at work right now. If I get a chance later I may open a pull request.

**Comment by gto76** [comment]
Fixed
