### ISSUE TITLE
Bytes encoding and decoding

### ISSUE THREAD

**Issue by luo3300612** [gto76/python-cheatsheet#25]
I learned that there are two ways to encode and decode bytes. One has been included:
```
<bytes> = <str>.encode(encoding='utf-8')
<str>   = <bytes>.decode('utf-8') 
```
the other is
```
<bytes> = bytes(<str>,encoding='utf-8')
<str> = str(<bytes>,encoding='utf-8')
```
Just to remind:-D. May be you just choose the one you prefer~

**Comment by gto76** [comment]
Thanks,
I prefer my version because it has words 'encode' and 'decode'. I'll leave it unchanged for now.

**Comment by gto76** [comment]
I added the 2 missing examples in the comments:
https://gto76.github.io/python-cheatsheet/#encode-1
