### ISSUE TITLE
Virtual environment, tests, setuptools and pip

### ISSUE THREAD

**Issue by javier-m** [gto76/python-cheatsheet#26]
I love this cheat sheet!
It would be great to add some points about how to make production-grade code, such as:
- virtual environment (e.g., with virtualenvwrapper)
- test (unittest, pytest, mock, tox)
- packaging and installation (setuptools, pip, ...)

Some points about how "import" works would be great too (one of the most used yet not understood feature in Python)
I realize that those are quite broad topics (especially the last one), but that would sure be very helpful

**Comment by gto76** [comment]
I think I will not cover those and try to keep the cheatsheet only about the syntax and libraries.
It is very long as is, and it will probably grow a little more in the future.

**Comment by gto76** [comment]
I added the link in the [FAQ](https://github.com/gto76/python-cheatsheet/wiki/Frequently-Asked-Questions) section of the Wiki to the [The Hitchhiker’s Guide to Python](https://docs.python-guide.org/), that covers that topics.
