### ISSUE TITLE
Sorting convenience functions?

### ISSUE THREAD

**Issue by harkabeeparolus** [gto76/python-cheatsheet#34]
I wonder if you’ve considered the operator convenience functions itemgetter and attrgetter for list sorting:

https://docs.python.org/3.7/howto/sorting.html#operator-module-functions

I find them cleaner than using lambda functions, and the documentation claims that they also have better performance.

**Comment by gto76** [comment]
Examples of sorting with itemgetter are in Operator section.

I like to use lambdas in first examples to show less ambiguosly that key argument needs to be a function.

Anyways, it's one of those tabs vs spaces areas. I sincerely hope I didn't trigger anyone with my answer.

**Comment by harkabeeparolus** [comment]
Sounds good to me! You have a valid reason for using lambdas. 🙂
