### ISSUE TITLE
Exceptions need more details

### ISSUE THREAD

**Issue by ntindle** [gto76/python-cheatsheet#56]
Firstly, nice doc. 

For exceptions, having a comment on which is executed for what failures would be good for **else** and **finally**

**Comment by gto76** [comment]
So I guess you would like it to be something like this:

```python
try:
    <code_1>           # Executed fully or until some error happens.
except <exception_a>:
    <code_2_a>         # Executed if exception_a happens in code_1.
except <exception_b>:
    <code_2_b>         # Executed if exception_b happens in code_1.
else:
    <code_2_c>         # Executed if code_1 had no exceptions.
finally:
    <code_3>           # Executed at the end in any event.
```

Or this:
```python
try:
    <code_1>
except <exception_a>:
    <code_2_a>
except <exception_b>:
    <code_2_b>
else:
    <code_2_c>
finally:
    <code_3>
```
* **Else block executes if there were no errors raised inside the try block.**
* **Finally block executes in any case.**

I think the first one is too cluttered, but the second one could work.
Does anybody else have an opinion on this?

**Comment by ntindle** [comment]
2nd one is better. 
1st is more descriptive but I agree it is far too cluttered

**Comment by gto76** [comment]
Done: https://gto76.github.io/python-cheatsheet/#exceptions

Thanks
