### ISSUE TITLE
More elegant way to calculate the product of the elements

### ISSUE THREAD

**Issue by mariosasko** [gto76/python-cheatsheet#60]
In python 3.8 there is a more elegant way to calculate the product of the elements. 

Instead of 
`product_of_elems = functools.reduce(lambda out, el: out * el, <collection>)`
it can be done like this
`product_of_elems = math.prod(<collection>)`

**Comment by Heritwiz** [comment]
But this is not worth creating an issue 😉😎

**Comment by gto76** [comment]
Thanks. I will not change it now because it's a 3.8 feature and everything else in the cheatsheet only requires version 3.7. Maybe in the future.
