### ISSUE TITLE
Add a directory with hyperlinks

### ISSUE THREAD

**Issue by DanBrown47** [gto76/python-cheatsheet#67]
Add a directory on top of the Readme to skip to desired stuff

**Comment by gto76** [comment]
Is it possible though?
I think I tried it once with HTML tags, something like:
    `<code><a href="...">...</a></code>`
But it did't work.

**Comment by DanBrown47** [comment]
It should work, Try putting code tags inside a tag

**Comment by collinsuzebu** [comment]
seems this issue has been resolved now.
