### ISSUE TITLE
Text on plotly Graph is not clear

### ISSUE THREAD

**Issue by Joe-Sin7h** [gto76/python-cheatsheet#81]
Code For plotly can be changed to make it look more clear in dark background.
![Capture](https://user-images.githubusercontent.com/58473917/101313272-d9bb5d80-387b-11eb-8a8d-b4715c0b351b.JPG)

**Comment by rajUwU** [comment]
Hey, i would like to contribute in this issue as this is my first time contributing, I can reproduce this issue and would like to work on it. can i be assigned to this task?

**Comment by gto76** [comment]
Background was changed to a lighter color.
